### PR TITLE
Make sure to install enterprise_key before installing bundle

### PR DESCRIPTION
**Pull request by felixheidecke**
Fixes: https://github.com/owncloud/market/issues/165

### CODE REVIEW

**Comment by davitol** [comment]
screen shot 2017-09-15 at 14 17 02
Keeps faiing. Tried on owncloud-daily-master.tar.bz2 applying this PR on ubuntu 16.04

**Comment by patrickjahns** [comment]
Tested and works for me.

**Comment by davitol** [comment]
Retested and as said it fails for me

screen shot 2017-09-27 at 15 45 17

**Comment by patrickjahns** [comment]
Options from here on:

1) implement the `installInfo` field that provides an order for the frontend to execute

2) implement an endpoint where the frontend can ask for information of an application - and only attempt to install other things, when enterprise_key app is installed

**Comment by felixheidecke** [comment]
This is definitely a task for the business logic! Frontend should remain as dumb as possible.

**Comment by patrickjahns** [comment]
Then we probably should go this way:
frontend calls a backend route `/bundles/<bundle_id>/install" and the backend can handle install tasks. 
how should the frontend then be informed on updates?

**Comment by felixheidecke** [comment]
> how should the frontend then be informed on updates?

Just send the appropriate response + a nice msg ;-)

**Comment by PVince81** [comment]
Is this ready ? What's missing ?

This is blocking another task currently.

**Comment by DeepDiver1975** [comment]
> Then we probably should go this way:
> frontend calls a backend route `/bundles/<bundle_id>/install" and the backend can handle install tasks.

Bad from a UX pov - since you get no feedback for installation of individual tasks.

**Comment by patrickjahns** [comment]
> Bad from a UX pov - since you get no feedback for installation of individual tasks.

That's why I asked: 

> how should the frontend then be informed on updates?

----------

If the frontend takes care of sending individual requests - what happens when one application of 10 applications fails? Is it valid that the other applications are installed, or should the application do a rollback?

Moving the logic in the frontend seems not right - the frontend should only be concerned with triggering the install process. The handling for error cases should thus be done on the backend. 

---------

Regarding
> Bad from a UX pov - since you get no feedback for installation of individual tasks.

If the backend provides a route for the frontend to ask what is the status? Something among the lines:
GET `/bundles/<bundle_id>/installStatus` ?
The backend could then provide:
```
{
  "app1": {
     "status": "not_installed"
   },
  "app2": {
     "status": "installing"
   },
  "app3": {
     "status": "installed"
   }
}
```

**Comment by DeepDiver1975** [comment]
I have my own view on this with respect to simplicity:
- first of all this dependency between enterprise_key app and all other should no exist in the first place
- we will add this exception with the lowest impact
- I'd just add this logic snippet to the front end
- please note that we will remove this dependency most likely - see discussion about moving the key app to core

**Comment by davitol** [comment]
Move to development milestone?

**Comment by felixheidecke** [comment]
@davidtol pls have a look :-)

**Comment by davitol** [comment]
Tested and the order installing went fine. But it seems to take much longer in installing the whole bundle than before. Anyway :+1:

**Comment by felixheidecke** [comment]
@davitol … that may be due to the single threaded installation process. No async app installation anymore.

**Pull request merged**
