### PR TITLE
Choose the correct app release when updating

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by PVince81** [comment]
How to reproduce ? Is this happening when an app provides multiple versions ? Guests app I guess since it's the only one with two releases ?

@davitol something to test as well

**Comment by DeepDiver1975** [comment]
> How to reproduce ? Is this happening when an app provides multiple versions ? Guests app I guess since it's the only one with two releases ?

on marketplace.int.owncloud.com there are two contacts app releases

**Comment by DeepDiver1975** [comment]
due to no sorting before this fix in results in random behavior

**Comment by PVince81** [comment]
random behavior in what situation ? when an app provides more than one version I guess ?

**Comment by PVince81** [comment]
ok, got it.

@davitol can you test ?

**Comment by DeepDiver1975** [comment]
> random behavior in what situation ? when an app provides more than one version I guess ?

we shall add some sorting on the api in the marketplace as well maybe .....

**Comment by PVince81** [comment]
@DeepDiver1975 fixing sorting in the marketplace side sounds reasonable, could avoid having to do another RC for this fix here.

**Comment by PVince81** [comment]
We'll still do a RC5 with this PR

**Comment by davitol** [comment]
:+1: WFM

**Pull request merged**
