### PR TITLE
Hide 'Edit/Add API Key' button if not changeable

### PR DESCRIPTION
**Pull request by felixheidecke**
The late PR: https://github.com/owncloud/market/pull/155

### CODE REVIEW

**Comment by patrickjahns** [comment]
This is failing - if it should be included in 0.2.3 it needs to be fixed and based against release branch - otherwise please move to development milestone

**Comment by patrickjahns** [comment]
moved to development for next release - please fix accordingly @felixheidecke

**Comment by PVince81** [comment]
@felixheidecke please finish

**Comment by felixheidecke** [comment]
@hurradieweltgehtunter do you know if this is still an issue?

**Comment by PVince81** [comment]
@IljaN do you know ?

**Comment by IljaN** [comment]
I'll check

**Pull request merged**
