### PR TITLE
Merge back Release 0.5.1

### PR DESCRIPTION
**Pull request by HanaGemela**
Closes https://github.com/owncloud/market/issues/582

### CODE REVIEW

**Comment by phil-davis** [comment]
merge-back is going to be tricky. https://github.com/owncloud/market/releases/tag/v0.6.0 is already in `master`

Somebody needs to make a "copy" of this branch, rebase it, resolve conflicts, and see what are the useful changes that actually need to be applied to `master`

**Comment by HanaGemela** [comment]
@IljaN could you have a look at the conflicts? No rush, when you are back from your holidays

**Comment by IljaN** [comment]
@HanaGemela We shouldn't merge this back and instead keep the release-0.5.1  branch as the changes in 0.5.1 is only the message to upgrade to 10.5. So now we have two parallel versions 0.5.1 for < 10.5 and 0.6.0 for > 10.5

/cc @micbar

**Comment by IljaN** [comment]
Or actually we don't need to keep the branch as we have the v0.5.0 tag

**Comment by phil-davis** [comment]
Removed myself from "review requests" so that this does not keep showing up in my "reviews pending" list.

**Pull request closed without merging**
