### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by PVince81**
@DeepDiver1975 I preemptively added https://github.com/owncloud/market/pull/125/.

Will need to backport the changelog to stable10 as well

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
hmm - this changelog is based on core but the app has a version itself and is released on the marketplace

shall we maintain 2 changelogs?

**Comment by PVince81** [comment]
@DeepDiver1975 good point... The core build will tag this repo with v10.0.3, etc version but marketplace has a different version...

Let's use only one changelog but with the app's own version scheme.

Later on once we have a bundling script we could build the core release by pulling the latest compatible "market" app.

**Comment by PVince81** [comment]
cc @pmaier1 @felixboehm in case you have better ideas ^

**Comment by PVince81** [comment]
we could use both versions in an entry: 10.0.3 / 1.2.3

**Comment by PVince81** [comment]
I added the second version as well, and increased the app version to 0.1.1.

When we replace "Unreleased" it will say "10.0.3 / 0.1.1".

If we need to release a new market version on the marketplace as a hotfix, then the changelog will have a new section "10.0.3 / 0.1.2"

@pmaier1 are you ok with this ?

**Comment by PVince81** [comment]
seems my changes got lost in a rebase

**Comment by PVince81** [comment]
stable10: bcecfcb07422b822e95efb1171e043ba5eee7809

**Comment by patrickjahns** [comment]
I am a bit confused - since we already published 0.2.1 on marketplace: https://marketplace.owncloud.com/apps/market

**Pull request merged**
