### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by PVince81**
Ran npm update

### CODE REVIEW

**Comment by PVince81** [comment]
did a quick test of the market app:
- installing apps
- setting API key
- starting trial
- installing enterprise bundle

all worked fine

**Comment by PVince81** [comment]
@felixheidecke please review

**Comment by felixheidecke** [comment]
@PVince81 did you forget to add package.json?

**Comment by PVince81** [comment]
I just ran it again and rebased.

indeed I forgot package.json for some reason

**Comment by felixheidecke** [comment]
As these are all devDependencies, all should work fine if it still compiles.

**Pull request merged**
