### PR TITLE
Fix key when mapping the result

### LINKED ISSUE #383: market upgrade command does not work with --all version
Tested in oC 10.0.8 with market app version 0.2.4 and in oC 10.0.9 with market app version 0.2.5 rc2

### Steps to reproduce
1. Get an oC Server with 2 apps that have a newer version not installed yet
2. Run command `./occ market:upgrade --list` and check there are newer versions available
3. Run command `sudo -u www-data ./occ market:upgrade --all`

### Expected behaviour
The apps should be upgraded

### Actual behaviour
A warning is shown `: Not installed ...`  and the apps are not upgraded

screen shot 2018-07-26 at 12 56 49
And the help of the command shows:

screen shot 2018-07-26 at 12 51 54

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #383 

TL;DR 
https://github.com/owncloud/market/blob/master/lib/MarketService.php#L326

### Testing
0. Have any app to update from market
1. Try to do the update with `occ market:upgrade --all`

Before
```
deo@jah-mobile:1008> php occ market:upgrade --list
market : 0.2.5
deo@jah-mobile:1008> php occ market:upgrade --all
: Not installed ...
```

After
```
deo@jah-mobile:1008> php occ market:upgrade --all
market: Installing new version 0.2.5 ...
market: App updated.
```

### CODE REVIEW

**Comment by PVince81** [comment]
any chance to add a unit test here with the CommandTester ?

**Comment by VicDeo** [comment]
hm... ok

**Comment by VicDeo** [comment]
can't run tests locally...
```
deo@jah-mobile:~/public_html/oc-tmp/apps/market> ../../lib/composer/bin/phpunit --configuration phpunit.xml
PHP Fatal error:  Uncaught Error: Class 'OC_Util' not found in /home/deo/public_html/oc-tmp/lib/base.php:566
Stack trace:
#0 /home/deo/public_html/oc-tmp/lib/base.php(1007): OC::init()
#1 /home/deo/public_html/oc-tmp/tests/bootstrap.php(9): require_once('/home/deo/publi...')
#2 /home/deo/public_html/oc-tmp/lib/composer/phpunit/phpunit/src/Util/Fileloader.php(52): include_once('/home/deo/publi...')
#3 /home/deo/public_html/oc-tmp/lib/composer/phpunit/phpunit/src/Util/Fileloader.php(36): PHPUnit_Util_Fileloader::load('/home/deo/publi...')
#4 /home/deo/public_html/oc-tmp/lib/composer/phpunit/phpunit/src/TextUI/Command.php(914): PHPUnit_Util_Fileloader::checkAndLoad('/home/deo/publi...')
#5 /home/deo/public_html/oc-tmp/lib/composer/phpunit/phpunit/src/TextUI/Command.php(739): PHPUnit_TextUI_Command->handleBootstrap('/home/deo/publi...')
#6 /home/deo/public_html/oc-tmp/lib/composer/phpunit/phpunit/src/TextUI/Command.php(127): PHPUnit_TextUI_Command->handleArguments(Array)
#7 /home/deo/public_html/oc-tmp/lib/composer/phpunit/phpunit in /home/deo/public_html/oc-tmp/lib/base.php on line 566
```

**Comment by VicDeo** [comment]
100% coverage :grin:

**Comment by VicDeo** [comment]
@PVince81 do we release the app from master?

**Comment by PVince81** [comment]
@VicDeo yes. The release script grabs the latest version from marketplace when bundling

**Comment by VicDeo** [comment]
ok. no backport then

**Pull request merged**
