### PR TITLE
Scrutinizer Auto-Fixes

### PR DESCRIPTION
**Pull request by scrutinizer-auto-fixer**
@DeepDiver1975 requested this pull request.

It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/owncloud/market/

### CODE REVIEW

**Comment by individual-it** [comment]
so what is the coding standard in oC?
looking into the oC code I see.
1. different ways to concatenate, sometime with, sometimes without spaces around "." 
2. usually a space before "{" in function/class definition. That is also the way the examples show in the documentation https://doc.owncloud.org/server/10.0/developer_manual/general/codingguidelines.html#php

would be good to agree on a standard. I would like to have an "official" phpcs.xml file https://github.com/owncloud/core/pull/28519

**Comment by DeepDiver1975** [comment]
> different ways to concatenate, sometime with, sometimes without spaces around "."

generally speaking - I prefer string interpolation over concatenate 😉 
but if we concatenate - there shall be spaces

THX for taking the task about fixing the coding style 🎉

**Comment by VicDeo** [comment]
@DeepDiver1975 
>but if we concatenate - there shall be spaces

I think the same way... but this PR strips the spaces in concatenation.

**Comment by DeepDiver1975** [comment]
reverting ....

**Pull request merged**
