### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by felixheidecke**
Update dependencies. Build and UI tests work as expected.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Still red

**Comment by PVince81** [comment]
obsolete ?

**Comment by felixheidecke** [comment]
Still have no Idea what this means https://github.com/owncloud/market/pull/325#issuecomment-384555856

**Comment by PVince81** [comment]
to be redone, see dependabot PRs

**Pull request closed without merging**
