### PR TITLE
Show date only if available. Show more detailed update information.

### PR DESCRIPTION
**Pull request by felixheidecke**
Fixes: https://github.com/owncloud/market/issues/144

### CODE REVIEW

**Comment by patrickjahns** [comment]
The idea is nice - yet now when clicking on "update" i see two buttons doing an action:
double update button

**Comment by patrickjahns** [comment]
@davitol 
Can you please review and confirm

**Comment by davitol** [comment]
@patrickjahns 👎 It doesnt work for me, when there's an app to update I get a blank page. No logs in owncloud.log. Tested with today's daily master

screen shot 2017-09-26 at 10 09 12

**Comment by patrickjahns** [comment]
@davitol  please test against stable 10.0.3

**Comment by davitol** [comment]
> @davitol please test against stable 10.0.3

The server got updated and same behaviour. Does it work for you in 10.0.3 @patrickjahns ?

**Comment by DeepDiver1975** [comment]
> @patrickjahns 👎 It doesnt work for me, when there's an app to update I get a blank page. No logs in owncloud.log. Tested with today's daily master

But this issues looks unrelated to this PR.

**Comment by DeepDiver1975** [comment]
> Does it work for you in 10.0.3

works for me

**Comment by patrickjahns** [comment]
Actually I also found some issue when re-testing today:

Without available update - everything is fine.

Once I enable an app that has an update - i see this error in console
@davitol  - next time please send a more detailed error report so we know where to look for what

**Comment by patrickjahns** [comment]
Okay - the issue I encountered was due to using guests app 0.3.1 and market at the same time - this somehow broke the marketplace frontend with the issue mentioned above

**Comment by DeepDiver1975** [comment]
> Okay - the issue I encountered was due to using guests app 0.3.1 and market at the same time - this somehow broke the marketplace frontend with the issue mentioned above

we did fix this already ... 0.4.x I guess ....

**Comment by felixheidecke** [comment]
Travis keeps failing with `sh: 1: webpack: not found`
Whats up with that?
@DeepDiver1975

**Comment by felixheidecke** [comment]
I guess this will fix it? https://github.com/owncloud/market/pull/171

**Pull request merged**
