### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by felixheidecke**
- Purge fixed js-beautify dependency
- Update dependencies overall

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
git leason 2: please squash your commits ;-)

**Comment by felixheidecke** [comment]
> git leason 2: please squash your commits ;-)

I'll do that after the review is thru. Who knows how many more commits will come. Cool?

**Comment by patrickjahns** [comment]
Do we need to backport this?

**Comment by DeepDiver1975** [comment]
> Do we need to backport this?

I really hope we can come up with a solution for 10.0.4 where we take apps like market from the marketplace so that we need to maintain only one branch in the individual app repos

**Pull request merged**
