### PR TITLE
fix: drop snyk

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Review by jnweiger — COMMENTED** [review]
snyk.io seems to be a security checker. Do we have other scanners, that should be run instead?

**Comment by xoxys** [comment]
> snyk.io seems to be a security checker. Do we have other scanners, that should be run instead?

Yes.

image

**Comment by DeepDiver1975** [comment]
and GH dependabot is also handling security related topics ...

:exclamation: Security :four: :seven: :exclamation: 

image

**Comment by DeepDiver1975** [comment]
> Interesting: According to

nothing special - sec tools are software and software has vulnerabilities ..... :shrug:

**Pull request merged**
