### PR TITLE
add a note to explain where to get api key

### LINKED ISSUE #463: Usability improvement: add link to marketplace in warning about missing API key
This should be a quick and easy one:

when the error message about a missing API key appears, please add a note on where to get it.
This will save a lot of people in the company the time and effort to write an email explaining the process over and over again every single time.

Example:
"Marketplace API key missing. Get one at https://marketplace.owncloud.com/"

### PR DESCRIPTION
**Pull request by karakayasemi**
resolves #463 
PR adds a text to start-enterprise-trial modal that explains where a user can get an API key. 

@dercorn I made several grep searches in the repo and I found the message "API key missing" only here. I hope it is the place that you suggested to add an explanation.

## Screenshot
image

### CODE REVIEW

**Comment by PVince81** [comment]
@karakayasemi mind posting a screenshot ?

**Comment by karakayasemi** [comment]
I added screenshot to PR description.

**Comment by PVince81** [comment]
thanks.

some wording improvements:
"Please copy it from your profile page on the Marketplace."

"Then enter the API key here" (add "the")

**Comment by karakayasemi** [comment]
@PVince81 I made the suggested changes and updated the screenshot. Please review again. Thanks.

**Comment by davitol** [comment]
@karakayasemi Tested with market 0.5.0. RC1 tarball located here https://github.com/owncloud/market/releases/tag/v0.5.0RC1 and I cannot see the text added. Any clue?

**Comment by davitol** [comment]
Checked that text does not appear using 10.2.0 complete Enterprise tarball, but it works with the community one.

Screen Shot 2019-06-07 at 10 35 12

**Comment by karakayasemi** [comment]
@davitol, the problem is not related with this change. 
When you install enterprise tarball with the way that discussed in the chat (`occ market:install`), the new version of market app is installing under `apps-external` folder which folder is the writable one in the `config.php` and the old version is still remaining under `apps` folder.

After the installation the ownCloud instance is somehow loading old app's js file. If you remove the old app from `apps` folder, the problem is resolving. We need investigation for behavior of `occ market:install`' command.

**Pull request merged**
